//! Schema, the connection wrapper, and the vote/story queries.
//!
//! There is a migration system now, and it is as small as one can be:
//! `meta.schema_version` says which shape a database has, `MIGRATIONS` holds
//! one SQL batch per version, and `open_db` applies the missing ones under an
//! advisory lock. `SCHEMA` stays the documented, final shape, and a fresh
//! database gets it directly rather than replaying history. Those are two
//! paths to the same place, which is only acceptable because
//! `tests/migration.rs` asserts they arrive at identical catalogs.

use std::cell::{Cell, RefCell};

use bytes::BytesMut;
use postgres::types::{to_sql_checked, FromSql, IsNull, ToSql, Type};
use postgres::{Client, Error, NoTls, Row};
use serde::Serialize;

use crate::dates::now_seconds;

/// Which shape of the schema this binary expects. Bumped with every entry
/// added to `MIGRATIONS`; a database ahead of it is refused at boot.
pub const SCHEMA_VERSION: i64 = 3;

/// The users table as migration 1 created it, frozen: a migration is never
/// edited, and this is the shape migration 2 starts from. The fresh path uses
/// `USERS_TABLE` below.
const USERS_TABLE_V1: &str = "
CREATE TABLE IF NOT EXISTS users (
  -- START WITH 2: user 1 is inserted below with an explicit id, and an
  -- explicit id does not advance a BY DEFAULT identity — without this the
  -- first `user add` would be handed 1 and fail on the owner.
  id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2),
  name          TEXT   NOT NULL UNIQUE,
  -- sha256 of the token, never the token. Every PR preview is restored from
  -- a dump of production and is readable by anyone who can read the PR, so a
  -- plaintext column would hand out every user's login with every preview.
  -- NULL means no way in yet: user 1 after the migration, until a token is
  -- minted for it.
  token_hash    BYTEA  UNIQUE,
  created_at    BIGINT NOT NULL,
  -- The round state that lived in `meta` beside `last_sync_at`. A round is a
  -- fact about a user; the sync stamp is a fact about the corpus and stays.
  round_seq     BIGINT NOT NULL DEFAULT 0,
  current_round TEXT,                    -- the Round JSON, as meta held it
  last_train_at BIGINT
);
-- Fresh databases get an owner too, so dev mode has someone to be and the
-- fresh and migrated shapes agree on who owns the first vote.
INSERT INTO users (id, name, created_at)
  VALUES (1, 'owner', extract(epoch from now())::bigint)
  ON CONFLICT (id) DO NOTHING;
";

/// The users table, shared verbatim by the fresh path and (in pieces)
/// migration 2 so the two cannot spell it differently.
///
/// A user is a row; a credential is a row in `login_links` or `sessions`
/// below, never a column here. `docs/multi-user.md`, "What a user is".
///
/// `display_name` is nullable and not unique: the operator creates a user
/// knowing at most an email, and the invitee picks their own name when the
/// link is opened — NULL is the "invited, not set up yet" state the UI asks
/// about. People choose colliding names and rename themselves, so the name
/// is never the handle the CLI addresses a user by; `id` or `email` is.
///
/// `email` is nullable too — user 1 has none after the migration, dev mode
/// has none, and a friend handed a link over chat need not give one — and is
/// unique case-insensitively (`users_email_key`, on `lower(email)`), stored
/// as typed because it is what mail would be sent to. It is the one column
/// that is personal data: every preview seed scrubs it (`preview.yml`).
///
/// `email` is the *last* column, where `ADD COLUMN` put it on the migrated
/// database; the catalogs of the two paths are compared column for column.
const USERS_TABLE: &str = "
CREATE TABLE IF NOT EXISTS users (
  -- START WITH 2: user 1 is inserted below with an explicit id, and an
  -- explicit id does not advance a BY DEFAULT identity — without this the
  -- first invite would be handed 1 and fail on the owner.
  id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 2),
  display_name  TEXT,                    -- NULL until the invitee picks one
  created_at    BIGINT NOT NULL,
  -- The round state that lived in `meta` beside `last_sync_at`. A round is a
  -- fact about a user; the sync stamp is a fact about the corpus and stays.
  round_seq     BIGINT NOT NULL DEFAULT 0,
  current_round TEXT,                    -- the Round JSON, as meta held it
  last_train_at BIGINT,
  email         TEXT                     -- NULL for the owner, dev mode, link-only friends
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (lower(email));
-- Fresh databases get an owner too, so dev mode has someone to be and the
-- fresh and migrated shapes agree on who owns the first vote.
INSERT INTO users (id, display_name, created_at)
  VALUES (1, 'owner', extract(epoch from now())::bigint)
  ON CONFLICT (id) DO NOTHING;
";

/// The two credential tables, shared verbatim by the fresh path and
/// migration 2.
///
/// Two tables rather than one `tokens(kind)`: different lifetimes, different
/// columns, different access paths. `authorize()` only ever reads `sessions`;
/// redemption only ever reads `login_links`; a `kind` column would put a
/// `WHERE kind =` on every query that one of them could forget.
///
/// Both store `sha256(token)` and never the token. Every PR preview is
/// restored from a dump of production and is readable by anyone who can read
/// the PR, so a plaintext column would hand out every login with every
/// preview. The plaintext exists once, in the response that minted it.
const CREDENTIAL_TABLES: &str = "
-- Short-lived, counted-use. An invite and a 'mail me a login' are the same
-- row; the only difference is whether display_name is still NULL when it is
-- redeemed. max_uses is 1 for a person and more for a link that must serve a
-- crowd — the PR preview comment, read by everyone on the PR.
CREATE TABLE IF NOT EXISTS login_links (
  token_hash BYTEA  PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  uses       BIGINT NOT NULL DEFAULT 0,
  max_uses   BIGINT NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_login_links_user ON login_links(user_id, created_at DESC);

-- Long-lived, one per device. Redeeming a link inserts one and sets the
-- cookie; revoking a user's access is deleting their rows. Fixed expiry, no
-- sliding window: a sliding one is a write per request, and a page load is
-- twenty requests through one mutexed connection. last_seen_at is bumped at
-- most once a day (SESSION_TOUCH_SECS) — enough to say which phone that was.
CREATE TABLE IF NOT EXISTS sessions (
  token_hash   BYTEA  PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   BIGINT NOT NULL,
  expires_at   BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  label        TEXT                      -- User-Agent at creation
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
";

/// Invites, shared verbatim by the fresh path and migration 3.
///
/// A third token table, and it earns the row `tokens(kind)` would not: a
/// login link *authenticates a user who already exists*, an invite *mints
/// one*. `authorize()` reads `sessions`, `/login` reads `login_links`,
/// `/invite/…` reads this — three verbs, three tables, no `WHERE kind =` for
/// a query to forget. `docs/multi-user.md`, "Invites".
///
/// It is also the one credential table that is a **ledger**: the operator
/// asks it who has taken up an invite and when, so a spent row stays as
/// long as its user does. `revoked_at` rather than a DELETE for voiding, so
/// the decision is on record; `delete_invite` only ever takes a row nobody
/// is left of (`user_id IS NULL`) — a Slack unfurl spent two, and the users
/// it minted were removed, and neither row was history worth keeping.
///
/// `id` is the primary key and `token_hash` merely unique, because the
/// operator has to be able to name a row (`invite revoke 4`) using something
/// other than a secret they no longer hold — the plaintext exists once, in
/// the response that minted it.
///
/// No email column, deliberately: an invite does not know who will open it
/// (that is the whole point of `user_id`), and `users.email` is already the
/// one place an address lives. `note` is the operator's own bookkeeping —
/// "Anna, from work" — and is never shown to the person redeeming it.
///
/// Single use by construction: `redeemed_at` is a timestamp, not a counter.
/// A multi-use invite would make "who took it up" one-to-many and need an
/// audit table; the link that must serve a crowd is the PR preview's, and
/// that is a `login_links` row for user 1, not an invite.
const INVITES_TABLE: &str = "
CREATE TABLE IF NOT EXISTS invites (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token_hash  BYTEA  NOT NULL UNIQUE,
  note        TEXT,                    -- who the operator meant it for
  created_at  BIGINT NOT NULL,
  expires_at  BIGINT NOT NULL,
  redeemed_at BIGINT,                  -- NULL until someone opens it
  revoked_at  BIGINT,                  -- NULL unless the operator voided it
  -- Who it became. ON DELETE SET NULL, not CASCADE: `user remove` should not
  -- erase the fact that an invite was taken up, only who is left of it.
  user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_invites_created ON invites(created_at DESC);
";

/// Everything a fresh database needs, after `USERS_TABLE` and
/// `CREDENTIAL_TABLES`. Wrapped in an
/// advisory lock by `open_db` because the server, the trainer and the syncer
/// can all connect at boot: two sessions running `CREATE TABLE IF NOT EXISTS`
/// at once race in `pg_type` and one of them fails with a duplicate key error
/// rather than the no-op the statement promises.
///
/// `DOUBLE PRECISION`, never `REAL`: Postgres `REAL` is four bytes, and the
/// scores round-trip through it lossily. `BIGINT` throughout for the same
/// reason SQLite used `INTEGER` — HN item ids are already past 2^31.
///
/// `user_id` is the *last* column of every per-user table, which is where
/// `ALTER TABLE ... ADD COLUMN` put it on the migrated production database.
/// The catalogs of the two paths are compared column for column, and a
/// tidier position here would be the one difference.
const SCHEMA: &str = "
CREATE TABLE IF NOT EXISTS stories (
  id            BIGINT PRIMARY KEY,      -- Hacker News item id
  title         TEXT   NOT NULL,
  url           TEXT,
  domain        TEXT,
  author        TEXT,
  points        BIGINT NOT NULL DEFAULT 0,
  num_comments  BIGINT NOT NULL DEFAULT 0,
  created_at    BIGINT NOT NULL,         -- unix seconds, story creation
  day           TEXT   NOT NULL,         -- YYYY-MM-DD (UTC) for day grouping
  fetched_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stories_day ON stories(day);
CREATE INDEX IF NOT EXISTS idx_stories_created ON stories(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_comments ON stories(num_comments DESC);

-- One row per judged story per user. value: 1 = thumb up, -1 = thumb down,
-- 0 = skipped.
CREATE TABLE IF NOT EXISTS votes (
  story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  value      BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, story_id)
);
-- Every index a per-user query seeks on or sorts by leads with user_id,
-- because every such query now starts with `user_id = $n`.
CREATE INDEX IF NOT EXISTS idx_votes_created ON votes(user_id, created_at DESC);

-- Cached model scores so the feed can be sorted in SQL. A score is model
-- output, so it multiplies by users — the one table that grows with users x
-- corpus.
CREATE TABLE IF NOT EXISTS scores (
  story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  score      DOUBLE PRECISION NOT NULL,           -- probability of 'thumb up', 0..1
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0, -- 0..1, how much evidence backs the score
  model_rev  BIGINT NOT NULL,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, story_id)
);
CREATE INDEX IF NOT EXISTS idx_scores_score ON scores(user_id, score DESC);
-- The training queue seeks into the score axis instead of scanning it, so that
-- a multi-year archive costs the same as a week. Two expression indexes carry
-- that: the *unshrunk* offset from 0.5 (see RAW_OFFSET in service.rs — the
-- stored score is pulled toward 0.5 by confidence, so ranking on it ranks
-- ignorance rather than uncertainty), and confidence on its own for the slots
-- that deliberately hunt titles the model has no vocabulary for.
--
-- The `::double precision` casts are load-bearing. A bare `0.5` literal is
-- `numeric`, so the indexed expression would be numeric arithmetic while the
-- query's is float arithmetic; the two would not match after type resolution
-- and the planner would silently ignore the index. RAW_OFFSET in service.rs
-- must stay character-identical to this, modulo the `sc.` alias. A composite
-- `(user_id, expr)` index is opened only when the query says `user_id = $n`
-- *and* ranges on the expression — which is what every probe does.
CREATE INDEX IF NOT EXISTS idx_scores_raw_offset ON scores(user_id,
  ((score - 0.5::double precision)
   / (0.3::double precision + 0.7::double precision * confidence))
);
CREATE INDEX IF NOT EXISTS idx_scores_confidence ON scores(user_id, confidence);

-- Held-out predictions: for each voted story, what the model said about it
-- while it was in the fold that trained without it. Unlike the scores table,
-- this is not memorised: the trained model separates its own training set
-- perfectly, so only the out-of-fold number can disagree with a verdict.
-- Rewritten whole (per user) on every train; an empty table means no model
-- has held anything out yet.
CREATE TABLE IF NOT EXISTS oof_scores (
  story_id  BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  score     DOUBLE PRECISION NOT NULL,   -- probability of 'thumb up', 0..1
  model_rev BIGINT NOT NULL,
  user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, story_id)
);

-- The same, from the train before last. Kept for one reason: an accuracy move
-- between two revisions is a *paired* comparison — nearly the same votes, scored
-- twice — and the only honest test of it counts the votes whose prediction
-- actually flipped (McNemar). Without this table the two revisions can only be
-- compared as independent measurements, which cannot tell 'twelve flipped one
-- way' from 'thirty-five flipped, net twelve'.
--
-- One row per vote at most, so this doubles the held-out storage and nothing
-- more: it holds the previous revision only, never a history.
CREATE TABLE IF NOT EXISTS oof_previous (
  story_id  BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  score     DOUBLE PRECISION NOT NULL,
  model_rev BIGINT NOT NULL,             -- which revision held these out
  user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, story_id)
);

-- What the model predicted about a story at the instant it was judged.
-- The scores table cannot answer this after the fact: it is rewritten on every
-- retrain, and once a vote exists the model has memorised it (yes ~0.99). The
-- number captured here was a genuine out-of-sample guess — the vote it is
-- compared against did not exist when it was made — which is what makes
-- 'the brain called this one' an honest claim rather than a flattering one.
-- Cleared with the vote, so re-judging captures a fresh prediction.
CREATE TABLE IF NOT EXISTS vote_predictions (
  story_id   BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  score      DOUBLE PRECISION NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  model_rev  BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, story_id)
);

-- Serialised model snapshots (weights + metrics), newest revision wins.
-- `rev` is per user and dense — allocated as MAX(rev) + 1 for that user in
-- the INSERT (train_and_score), not by a sequence. Three things read it as a
-- count: the learning curve, the round summary (rev and rev + 1 are the two
-- ends of a round) and reset_models, whose contract is that numbering starts
-- again at 1. One trainer per process and one process per app make the
-- allocation safe; the composite key turns a race into a loud error.
CREATE TABLE IF NOT EXISTS models (
  rev        BIGINT NOT NULL,
  trained_at BIGINT NOT NULL,
  n_votes    BIGINT NOT NULL,
  payload    TEXT   NOT NULL,            -- JSON: weights, vocab, metrics
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, rev)
);

-- Corpus-wide facts: `last_sync_at`, `schema_version`. Per-user state lives
-- on `users`.
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
";

/// One batch per schema version, applied in order inside one transaction by
/// `open_db`; entry `n` takes a database from version `n` to `n + 1`. A
/// database from before this list existed has no `schema_version` and is
/// version 0.
///
/// A migration is written once and never edited: the databases it has already
/// run on will not run it again. New shape, new entry, `SCHEMA` updated to
/// match, and `tests/migration.rs` decides whether the two agree.
fn migrations() -> Vec<String> {
    vec![
        format!("{USERS_TABLE_V1}{MIGRATION_1}"),
        format!("{MIGRATION_2}{CREDENTIAL_TABLES}"),
        INVITES_TABLE.to_string(),
    ]
}

/// 0 → 1: users. `docs/multi-user.md`, "Schema". Runs after `USERS_TABLE_V1`.
///
/// `ADD COLUMN ... NOT NULL DEFAULT 1` is metadata-only (Postgres 11+), so
/// the existing rows are stamped user 1 without a rewrite; the default is
/// dropped straight after because a vote with no user is a bug, not a
/// default. Constraint names are spelled out to match what CREATE TABLE in
/// SCHEMA names them implicitly. Indexes are dropped and recreated with
/// user_id leading; on the real 52k-story database this is about a second,
/// most of it the `scores` primary key.
///
/// The round in flight is dropped, not carried: its votes are saved and train
/// at the next boundary, which is exactly what a stale round does.
const MIGRATION_1: &str = "
ALTER TABLE votes ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE votes ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE votes ADD CONSTRAINT votes_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE votes DROP CONSTRAINT votes_pkey;
ALTER TABLE votes ADD CONSTRAINT votes_pkey PRIMARY KEY (user_id, story_id);
DROP INDEX IF EXISTS idx_votes_created;
CREATE INDEX idx_votes_created ON votes(user_id, created_at DESC);

ALTER TABLE scores ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE scores ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE scores ADD CONSTRAINT scores_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE scores DROP CONSTRAINT scores_pkey;
ALTER TABLE scores ADD CONSTRAINT scores_pkey PRIMARY KEY (user_id, story_id);
DROP INDEX IF EXISTS idx_scores_score;
DROP INDEX IF EXISTS idx_scores_raw_offset;
DROP INDEX IF EXISTS idx_scores_confidence;
CREATE INDEX idx_scores_score ON scores(user_id, score DESC);
CREATE INDEX idx_scores_raw_offset ON scores(user_id,
  ((score - 0.5::double precision)
   / (0.3::double precision + 0.7::double precision * confidence))
);
CREATE INDEX idx_scores_confidence ON scores(user_id, confidence);

ALTER TABLE oof_scores ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE oof_scores ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE oof_scores ADD CONSTRAINT oof_scores_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE oof_scores DROP CONSTRAINT oof_scores_pkey;
ALTER TABLE oof_scores ADD CONSTRAINT oof_scores_pkey PRIMARY KEY (user_id, story_id);

ALTER TABLE oof_previous ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE oof_previous ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE oof_previous ADD CONSTRAINT oof_previous_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE oof_previous DROP CONSTRAINT oof_previous_pkey;
ALTER TABLE oof_previous ADD CONSTRAINT oof_previous_pkey PRIMARY KEY (user_id, story_id);

ALTER TABLE vote_predictions ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE vote_predictions ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE vote_predictions ADD CONSTRAINT vote_predictions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE vote_predictions DROP CONSTRAINT vote_predictions_pkey;
ALTER TABLE vote_predictions ADD CONSTRAINT vote_predictions_pkey PRIMARY KEY (user_id, story_id);

-- `rev` stops being an identity: it is allocated per user from now on, and
-- the sequence goes with the identity. The primary key becomes (user_id, rev).
ALTER TABLE models ALTER COLUMN rev DROP IDENTITY IF EXISTS;
ALTER TABLE models ADD COLUMN user_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE models ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE models ADD CONSTRAINT models_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE models DROP CONSTRAINT models_pkey;
ALTER TABLE models ADD CONSTRAINT models_pkey PRIMARY KEY (user_id, rev);

-- The owner's round state moves out of meta; only the corpus stamp stays.
UPDATE users SET
  round_seq     = COALESCE((SELECT value::bigint FROM meta WHERE key = 'round_seq'), 0),
  last_train_at = (SELECT value::bigint FROM meta WHERE key = 'last_train_at')
WHERE id = 1;
DELETE FROM meta WHERE key IN ('current_round', 'round_seq', 'last_train_at');
";

/// 1 → 2: a user stops being a token. `docs/multi-user.md`, "What a user is".
/// Runs before `CREDENTIAL_TABLES`.
///
/// `name` becomes `display_name`, nullable and no longer unique, because the
/// invitee picks it after the row exists. `token_hash` goes: it was never
/// populated anywhere (phase 2 never shipped against it), and credentials
/// live in their own tables now. `email` arrives last, which is where the
/// fresh `USERS_TABLE` spells it too. Dropping a column leaves a gap in
/// `attnum`, so `tests/migration.rs` compares column *order*, not position.
const MIGRATION_2: &str = "
ALTER TABLE users RENAME COLUMN name TO display_name;
ALTER TABLE users ALTER COLUMN display_name DROP NOT NULL;
ALTER TABLE users DROP CONSTRAINT users_name_key;
ALTER TABLE users DROP COLUMN token_hash;
ALTER TABLE users ADD COLUMN email TEXT;
CREATE UNIQUE INDEX users_email_key ON users (lower(email));
";

/// One arbitrary constant, shared by every process that opens the database.
/// Only the value matters, not what it spells. Public because the trainer
/// test holds it to park the worker thread at `open_db` on purpose.
pub const SCHEMA_LOCK: i64 = 4_919_420_187;

// The moral replacement for SQLite's `busy_timeout`: a query that has gone
// wrong errors instead of pinning a request thread forever. Generous enough
// that nothing legitimate here comes close — the slowest statement in the app
// is the corpus rescore, and that is a batched write measured in hundreds of
// milliseconds.
const STATEMENT_TIMEOUT: &str = "SET statement_timeout = '30s'";

/// A user, by id. A newtype rather than a bare `i64` for the worst bug this
/// design can grow: a parameter list `&[&story_id, &user]` written the other
/// way round compiles as two `i64`s, returns the wrong user's rows and fails
/// no test that has one user. With the newtype it does not compile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(transparent)]
pub struct User(pub i64);

impl User {
    /// User 1: the one every database has, the one dev mode acts as, and —
    /// while the app is single-user on the surface — the one every request
    /// is. Owns every vote that predates the users table.
    pub const OWNER: User = User(1);
}

impl ToSql for User {
    fn to_sql(
        &self,
        ty: &Type,
        out: &mut BytesMut,
    ) -> Result<IsNull, Box<dyn std::error::Error + Sync + Send>> {
        self.0.to_sql(ty, out)
    }

    fn accepts(ty: &Type) -> bool {
        <i64 as ToSql>::accepts(ty)
    }

    to_sql_checked!();
}

impl<'a> FromSql<'a> for User {
    fn from_sql(
        ty: &Type,
        raw: &'a [u8],
    ) -> Result<User, Box<dyn std::error::Error + Sync + Send>> {
        i64::from_sql(ty, raw).map(User)
    }

    fn accepts(ty: &Type) -> bool {
        <i64 as FromSql>::accepts(ty)
    }
}

/// Where the database lives; workers open their own connection here.
pub fn db_url() -> String {
    match std::env::var("DATABASE_URL") {
        Ok(u) if !u.is_empty() => u,
        _ => "postgres://postgres@localhost:5432/rekorderlig".to_string(),
    }
}

fn connect(url: &str) -> Client {
    // No TLS. The only deployment is a second machine on the same Fly app,
    // reached over 6PN — a WireGuard mesh that is already encrypted end to end
    // — and the alternative pulls rustls and a certificate story into a binary
    // whose whole shape is "one static musl file". If this ever has to cross a
    // public network, this function is the one place that changes.
    let mut client = Client::connect(url, NoTls).expect("connect to postgres");
    client
        .batch_execute(STATEMENT_TIMEOUT)
        .expect("statement_timeout");
    client
}

/// Whether an error means "this socket is gone", and so is worth one reopen.
///
/// `is_closed()` alone is not enough, and finding that out the hard way is why
/// the reconnect test exists: a backend killed under us surfaces as a plain
/// `ConnectionReset` I/O error, and `is_closed()` is false for it. The rule
/// that does hold is that anything the *server* answered carries a SQLSTATE —
/// a constraint violation, a syntax error, a statement timeout — and must
/// never be retried, while a connection that died before it could answer
/// carries an I/O error somewhere in its source chain and nothing else.
fn is_disconnect(e: &Error) -> bool {
    if e.is_closed() {
        return true;
    }
    if e.as_db_error().is_some() {
        return false;
    }
    let mut source = std::error::Error::source(e);
    while let Some(s) = source {
        if s.is::<std::io::Error>() {
            return true;
        }
        source = s.source();
    }
    false
}

/// A connection that survives the machine suspending.
///
/// Fly suspends the app machine to RAM when it is idle, so every socket held
/// across a suspend is dead on resume and the first statement after a visit
/// fails. `Db` reopens and retries that statement once, which is the whole
/// reason this is a wrapper rather than a bare `Client`.
///
/// Interior mutability (`RefCell`) rather than `&mut self`: the callers here
/// pass `&Db` down through closures and helper functions, exactly as they
/// passed `&Connection`, and `postgres::Client`'s `&mut self` methods would
/// have rewritten every signature in the crate for no behavioural gain. The
/// request path holds it behind a `Mutex`, workers own one each; nothing ever
/// shares one without that mutex, and every method here materialises its rows
/// before returning, so a borrow is never live across a call back into `Db`.
pub struct Db {
    url: String,
    client: RefCell<Client>,
    /// Whether a transaction is open. Two jobs: a statement inside one must
    /// never be silently retried on a reconnect (the transaction is already
    /// gone, and half of it would be replayed against a clean session), and
    /// `App::lock_db` uses it to roll back what a panicking handler left open.
    in_tx: Cell<bool>,
}

impl Db {
    fn reconnect(&self) {
        *self.client.borrow_mut() = connect(&self.url);
        self.in_tx.set(false);
    }

    /// Run `f`, and on a closed connection reopen and run it once more.
    ///
    /// Never retried inside a transaction: the disconnect already rolled that
    /// transaction back, so replaying one statement of it on a fresh session
    /// would commit a fragment. The error is reported instead.
    fn retrying<T>(&self, f: impl Fn(&mut Client) -> Result<T, Error>) -> Result<T, Error> {
        let first = f(&mut self.client.borrow_mut());
        match first {
            Err(e) if is_disconnect(&e) && !self.in_tx.get() => {
                self.reconnect();
                f(&mut self.client.borrow_mut())
            }
            other => other,
        }
    }

    pub fn execute(&self, sql: &str, params: &[&(dyn ToSql + Sync)]) -> Result<u64, Error> {
        self.retrying(|c| c.execute(sql, params))
    }

    /// Multiple statements in one round trip. No parameters, by definition.
    pub fn execute_batch(&self, sql: &str) -> Result<(), Error> {
        self.retrying(|c| c.batch_execute(sql))
    }

    pub fn query(&self, sql: &str, params: &[&(dyn ToSql + Sync)]) -> Result<Vec<Row>, Error> {
        self.retrying(|c| c.query(sql, params))
    }

    pub fn query_one(&self, sql: &str, params: &[&(dyn ToSql + Sync)]) -> Result<Row, Error> {
        self.retrying(|c| c.query_one(sql, params))
    }

    pub fn query_opt(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> Result<Option<Row>, Error> {
        self.retrying(|c| c.query_opt(sql, params))
    }

    /// Transactions are plain `BEGIN`/`COMMIT` statements rather than the
    /// crate's `Transaction` type, which borrows the client for its lifetime —
    /// and every batched write here calls helpers (`upsert_story`) that take
    /// `&Db` and would then be borrowing it a second time. The flag is what
    /// buys back the two things the typed API would have given: no retry
    /// across a transaction, and a stranded one rolled back before reuse.
    pub fn begin(&self) {
        self.execute_batch("BEGIN").expect("begin");
        self.in_tx.set(true);
    }

    pub fn commit(&self) {
        self.in_tx.set(false);
        self.execute_batch("COMMIT").expect("commit");
    }

    /// Roll back a transaction a panicking caller left open. A no-op when
    /// there is none, and it costs no round trip in that case.
    pub fn rollback_if_open(&self) {
        if self.in_tx.get() {
            self.in_tx.set(false);
            let _ = self.execute_batch("ROLLBACK");
        }
    }

    /// Kill this session's own backend, so the next statement meets a dead
    /// socket. Only the reconnect test wants this; production reaches the same
    /// state by being suspended to RAM and woken an hour later.
    pub fn terminate_for_test(&self) {
        // Straight at the client, not through `retrying`: going through it
        // would reconnect on the spot and hand the test back a live
        // connection, which is the opposite of what it asked for.
        let _ = self
            .client
            .borrow_mut()
            .execute("SELECT pg_terminate_backend(pg_backend_pid())", &[]);
    }
}

/// Open an independent connection to `url` (server, workers, tests, tooling),
/// and bring the database to `SCHEMA_VERSION` if it is not there yet.
///
/// One transaction, one lock: `pg_advisory_xact_lock` releases on commit, so
/// nothing has to remember to unlock it — including a process that dies
/// holding it. Every process that connects runs this; only the first does
/// anything, and the trainer and syncer starting beside it wait on the lock
/// and find it done.
pub fn open_db(url: &str) -> Db {
    let db = Db {
        url: url.to_string(),
        client: RefCell::new(connect(url)),
        in_tx: Cell::new(false),
    };
    db.begin();
    db.execute_batch(&format!("SELECT pg_advisory_xact_lock({SCHEMA_LOCK})"))
        .expect("schema lock");
    match schema_version(&db) {
        // No `meta` table at all: a fresh database gets the final shape
        // directly, never the history.
        None => {
            db.execute_batch(&format!(
                "{USERS_TABLE}{CREDENTIAL_TABLES}{INVITES_TABLE}{SCHEMA}"
            ))
            .expect("schema");
            stamp_version(&db, SCHEMA_VERSION);
        }
        Some(version) => {
            assert!(
                version <= SCHEMA_VERSION,
                "database schema is version {version}, this build knows {SCHEMA_VERSION}: \
                 an older binary against a newer database — restore, don't run"
            );
            for (i, migration) in migrations().iter().enumerate().skip(version as usize) {
                let to = i as i64 + 1;
                db.execute_batch(migration)
                    .unwrap_or_else(|e| panic!("migration to schema version {to}: {e}"));
                stamp_version(&db, to);
            }
        }
    }
    db.commit();
    db
}

/// `None` for a database with no `meta` table (fresh); `Some(0)` for one from
/// before `schema_version` existed.
fn schema_version(db: &Db) -> Option<i64> {
    let exists: bool = db
        .query_one("SELECT to_regclass('meta') IS NOT NULL", &[])
        .expect("meta lookup")
        .get(0);
    if !exists {
        return None;
    }
    Some(
        get_meta(db, "schema_version")
            .and_then(|v| v.parse().ok())
            .unwrap_or(0),
    )
}

fn stamp_version(db: &Db, version: i64) {
    set_meta(db, "schema_version", &version.to_string());
}

pub fn get_meta(db: &Db, key: &str) -> Option<String> {
    db.query_opt("SELECT value FROM meta WHERE key = $1", &[&key])
        .expect("get_meta")
        .map(|r| r.get(0))
}

pub fn set_meta(db: &Db, key: &str, value: &str) {
    db.execute(
        "INSERT INTO meta (key, value) VALUES ($1, $2) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        &[&key, &value],
    )
    .expect("set_meta");
}

/* ------------------------------------------------------------------- users */

/// How long a login link stays redeemable. A week, because the way a link
/// reaches a friend today is the operator pasting it into a chat, and a chat
/// is read when it is read. The mailed variant, when it exists, wants minutes
/// — this is the constant it will shorten, not a second mechanism.
pub const LINK_TTL_SECS: i64 = 7 * 86_400;

/// How long a device stays signed in. Fixed, not sliding (see `sessions`).
pub const SESSION_TTL_SECS: i64 = 365 * 86_400;

/// How stale `sessions.last_seen_at` may be before a request refreshes it.
/// One write a day per device instead of one per request.
pub const SESSION_TOUCH_SECS: i64 = 86_400;

/// The row behind a `User`, as the CLI lists it and `/api/stats` reports it.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct UserRecord {
    pub id: User,
    #[serde(rename = "displayName")]
    pub display_name: Option<String>,
    pub email: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
}

const USER_SELECT: &str = "SELECT id, display_name, email, created_at FROM users";

fn user_from_row(r: &Row) -> UserRecord {
    UserRecord {
        id: r.get(0),
        display_name: r.get(1),
        email: r.get(2),
        created_at: r.get(3),
    }
}

/// Why a user could not be created or changed. The one caller-caused failure
/// is a taken email; everything else panics like the rest of this module.
#[derive(Debug, PartialEq, Eq)]
pub enum UserError {
    EmailTaken,
}

/// Normalise an email the way the unique index compares it: trimmed, and
/// `None` for blank. Case is kept — `lower()` is the index's job, and the
/// address is stored as typed because it is what mail would go to.
fn clean_email(email: Option<&str>) -> Option<String> {
    email
        .map(str::trim)
        .filter(|e| !e.is_empty())
        .map(str::to_string)
}

/// A new user with no way in yet. Either field may be absent: the operator
/// often knows only an email, sometimes neither (a link handed over chat).
pub fn create_user(
    db: &Db,
    email: Option<&str>,
    display_name: Option<&str>,
) -> Result<User, UserError> {
    let email = clean_email(email);
    if let Some(email) = &email {
        if user_by_email(db, email).is_some() {
            return Err(UserError::EmailTaken);
        }
    }
    let display_name = display_name.map(str::trim).filter(|n| !n.is_empty());
    Ok(db
        .query_one(
            "INSERT INTO users (display_name, email, created_at) VALUES ($1, $2, $3) RETURNING id",
            &[&display_name, &email, &now_seconds()],
        )
        .expect("create_user")
        .get(0))
}

pub fn get_user(db: &Db, user: User) -> Option<UserRecord> {
    db.query_opt(&format!("{USER_SELECT} WHERE id = $1"), &[&user])
        .expect("get_user")
        .as_ref()
        .map(user_from_row)
}

pub fn user_by_email(db: &Db, email: &str) -> Option<UserRecord> {
    db.query_opt(
        &format!("{USER_SELECT} WHERE lower(email) = lower($1)"),
        &[&email.trim()],
    )
    .expect("user_by_email")
    .as_ref()
    .map(user_from_row)
}

/// The CLI's handle for a user: an id, or an email. Never the display name —
/// people pick colliding names and rename themselves.
pub fn find_user(db: &Db, handle: &str) -> Option<UserRecord> {
    if let Ok(id) = handle.trim().parse::<i64>() {
        return get_user(db, User(id));
    }
    user_by_email(db, handle)
}

pub fn list_users(db: &Db) -> Vec<UserRecord> {
    db.query(&format!("{USER_SELECT} ORDER BY id"), &[])
        .expect("list_users")
        .iter()
        .map(user_from_row)
        .collect()
}

/// Blank clears the name back to "not set up yet".
pub fn set_display_name(db: &Db, user: User, display_name: &str) {
    let display_name = Some(display_name.trim()).filter(|n| !n.is_empty());
    db.execute(
        "UPDATE users SET display_name = $2 WHERE id = $1",
        &[&user, &display_name],
    )
    .expect("set_display_name");
}

pub fn set_email(db: &Db, user: User, email: Option<&str>) -> Result<(), UserError> {
    let email = clean_email(email);
    if let Some(e) = &email {
        if user_by_email(db, e).is_some_and(|u| u.id != user) {
            return Err(UserError::EmailTaken);
        }
    }
    db.execute(
        "UPDATE users SET email = $2 WHERE id = $1",
        &[&user, &email],
    )
    .expect("set_email");
    Ok(())
}

/// The one destructive user operation: every vote, model, score and session
/// goes with the row (ON DELETE CASCADE). Returns whether there was a row.
pub fn delete_user(db: &Db, user: User) -> bool {
    db.execute("DELETE FROM users WHERE id = $1", &[&user])
        .expect("delete_user")
        > 0
}

/* ------------------------------------------------------------- credentials */

/// A fresh token: one `gen_random_uuid()` with the dashes out — 122 random
/// bits as 32 hex characters, minted by Postgres so this crate needs no RNG.
fn mint_token(db: &Db) -> String {
    db.query_one("SELECT replace(gen_random_uuid()::text, '-', '')", &[])
        .expect("mint_token")
        .get(0)
}

/// `sha256` of the token's bytes, as the tables store it. `convert_to`, not
/// `$1::bytea`: casting text to bytea parses it as bytea's escape format
/// rather than taking its bytes, and a token containing a backslash would hash
/// to something other than what was minted. (Minted tokens are hex, but a
/// candidate arriving in a cookie is whatever the client sent.)
const TOKEN_HASH: &str = "sha256(convert_to($1, 'UTF8'))";

/// A link, as minted: the plaintext token — returned once and never stored —
/// with the row's bounds, so a caller can say what it handed out.
#[derive(Debug, Clone, Serialize)]
pub struct LoginLink {
    pub token: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: i64,
    #[serde(rename = "maxUses")]
    pub max_uses: i64,
}

impl LoginLink {
    /// Where the browser redeems it. The path, not a URL: the server does not
    /// know its public hostname, and the CLI and the workflow each do.
    pub fn path(&self) -> String {
        format!("/login?t={}", self.token)
    }
}

/// Mint a login link for a user. `max_uses` is 1 for a person; the PR
/// preview asks for more, because one link in one comment serves every
/// reader of the PR.
pub fn create_login_link(db: &Db, user: User, max_uses: i64) -> LoginLink {
    let token = mint_token(db);
    let now = now_seconds();
    let expires_at = now + LINK_TTL_SECS;
    let max_uses = max_uses.max(1);
    db.execute(
        &format!(
            "INSERT INTO login_links (token_hash, user_id, created_at, expires_at, max_uses)
             VALUES ({TOKEN_HASH}, $2, $3, $4, $5)"
        ),
        &[&token, &user, &now, &expires_at, &max_uses],
    )
    .expect("create_login_link");
    LoginLink {
        token,
        expires_at,
        max_uses,
    }
}

/// Spend one use of a link. `None` for an unknown, expired or exhausted token
/// — the three are deliberately indistinguishable to the caller, since the
/// answer to all of them is "ask for a new one". One statement, so two
/// redemptions racing on the last use cannot both succeed.
pub fn redeem_login_link(db: &Db, token: &str) -> Option<User> {
    db.query_opt(
        &format!(
            "UPDATE login_links SET uses = uses + 1
             WHERE token_hash = {TOKEN_HASH} AND uses < max_uses AND expires_at > $2
             RETURNING user_id"
        ),
        &[&token, &now_seconds()],
    )
    .expect("redeem_login_link")
    .map(|r| r.get(0))
}

/// Sign a device in: a new session token, returned once. `label` is what the
/// device said it was (its User-Agent), so a list of sessions reads as a
/// list of phones rather than of hashes.
pub fn create_session(db: &Db, user: User, label: Option<&str>) -> String {
    let token = mint_token(db);
    let now = now_seconds();
    // A User-Agent can run to hundreds of characters; the label is for a
    // human reading a list.
    let label: Option<String> = label.map(|l| l.chars().take(120).collect());
    db.execute(
        &format!(
            "INSERT INTO sessions (token_hash, user_id, created_at, expires_at, last_seen_at, label)
             VALUES ({TOKEN_HASH}, $2, $3, $4, $3, $5)"
        ),
        &[&token, &user, &now, &(now + SESSION_TTL_SECS), &label],
    )
    .expect("create_session");
    token
}

/// Who a session token belongs to, if it is live. One indexed lookup per
/// request; the `last_seen_at` write happens at most once a day per device.
pub fn session_user(db: &Db, token: &str) -> Option<User> {
    let now = now_seconds();
    let row = db
        .query_opt(
            &format!(
                "SELECT user_id, last_seen_at FROM sessions
                 WHERE token_hash = {TOKEN_HASH} AND expires_at > $2"
            ),
            &[&token, &now],
        )
        .expect("session_user")?;
    let (user, last_seen): (User, i64) = (row.get(0), row.get(1));
    if now - last_seen >= SESSION_TOUCH_SECS {
        db.execute(
            &format!("UPDATE sessions SET last_seen_at = $2 WHERE token_hash = {TOKEN_HASH}"),
            &[&token, &now],
        )
        .expect("touch session");
    }
    Some(user)
}

/// Sign one device out. Idempotent: a token already gone is not an error.
pub fn delete_session(db: &Db, token: &str) {
    db.execute(
        &format!("DELETE FROM sessions WHERE token_hash = {TOKEN_HASH}"),
        &[&token],
    )
    .expect("delete_session");
}

/// Sign a user out everywhere and void their unspent links: what "revoke"
/// means. Returns how many sessions ended.
pub fn revoke_access(db: &Db, user: User) -> u64 {
    db.execute("DELETE FROM login_links WHERE user_id = $1", &[&user])
        .expect("revoke links");
    db.execute("DELETE FROM sessions WHERE user_id = $1", &[&user])
        .expect("revoke sessions")
}

/// A user's live devices, newest activity first.
#[derive(Debug, Clone, Serialize)]
pub struct SessionRecord {
    pub label: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    #[serde(rename = "lastSeenAt")]
    pub last_seen_at: i64,
    #[serde(rename = "expiresAt")]
    pub expires_at: i64,
}

pub fn list_sessions(db: &Db, user: User) -> Vec<SessionRecord> {
    db.query(
        "SELECT label, created_at, last_seen_at, expires_at FROM sessions
         WHERE user_id = $1 AND expires_at > $2 ORDER BY last_seen_at DESC",
        &[&user, &now_seconds()],
    )
    .expect("list_sessions")
    .iter()
    .map(|r| SessionRecord {
        label: r.get(0),
        created_at: r.get(1),
        last_seen_at: r.get(2),
        expires_at: r.get(3),
    })
    .collect()
}

/* ----------------------------------------------------------------- invites */

/// An invite, as minted: the plaintext token — returned once and never stored
/// — with when it stops working, so a caller can say what it handed out.
#[derive(Debug, Clone, Serialize)]
pub struct Invite {
    pub id: i64,
    pub token: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: i64,
    pub note: Option<String>,
}

impl Invite {
    /// Where it is redeemed. The path, not a URL: the server does not know
    /// its public hostname, and the CLI and the workflow each do.
    pub fn path(&self) -> String {
        format!("/invite/{}", self.token)
    }
}

/// An invite as the ledger reads back: what became of it, and who.
#[derive(Debug, Clone, Serialize)]
pub struct InviteRecord {
    pub id: i64,
    pub note: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    #[serde(rename = "expiresAt")]
    pub expires_at: i64,
    #[serde(rename = "redeemedAt")]
    pub redeemed_at: Option<i64>,
    #[serde(rename = "revokedAt")]
    pub revoked_at: Option<i64>,
    /// The user it minted — `None` while it is unredeemed, and again if that
    /// user has since been removed (the `redeemed_at` stamp stays either way).
    pub user: Option<UserRecord>,
}

/// Mint an invite. `note` is for the operator's list and reaches nobody else.
///
/// The same week as a login link, and for the same reason: the way an invite
/// reaches a friend is a paste into a chat, and a chat is read when it is
/// read.
pub fn create_invite(db: &Db, note: Option<&str>) -> Invite {
    let token = mint_token(db);
    let now = now_seconds();
    let expires_at = now + LINK_TTL_SECS;
    let note = note.map(str::trim).filter(|n| !n.is_empty());
    let id: i64 = db
        .query_one(
            &format!(
                "INSERT INTO invites (token_hash, note, created_at, expires_at)
                 VALUES ({TOKEN_HASH}, $2, $3, $4) RETURNING id"
            ),
            &[&token, &note, &now, &expires_at],
        )
        .expect("create_invite")
        .get(0);
    Invite {
        id,
        token,
        expires_at,
        note: note.map(str::to_string),
    }
}

/// Take up an invite: the row is claimed and a brand-new user is minted for
/// whoever opened it. `None` for a token that is unknown, expired, revoked or
/// already taken — indistinguishable to the caller on purpose, since the
/// answer to all four is "ask for a new one".
///
/// The claim is one statement, so two browsers racing on the same link cannot
/// both mint a user; the user row and the back-reference join it in one
/// transaction, so an invite is never stamped redeemed with nobody to show
/// for it. The name is left NULL — the invitee picks it, which is what the
/// welcome prompt asks for on the first screen.
pub fn redeem_invite(db: &Db, token: &str) -> Option<User> {
    let now = now_seconds();
    db.begin();
    let claimed: Option<i64> = db
        .query_opt(
            &format!(
                "UPDATE invites SET redeemed_at = $2
                 WHERE token_hash = {TOKEN_HASH}
                   AND redeemed_at IS NULL
                   AND revoked_at IS NULL
                   AND expires_at > $2
                 RETURNING id"
            ),
            &[&token, &now],
        )
        .expect("claim invite")
        .map(|r| r.get(0));
    let Some(invite) = claimed else {
        db.rollback_if_open();
        return None;
    };
    let user: User = db
        .query_one(
            "INSERT INTO users (created_at) VALUES ($1) RETURNING id",
            &[&now],
        )
        .expect("invite creates a user")
        .get(0);
    db.execute(
        "UPDATE invites SET user_id = $2 WHERE id = $1",
        &[&invite, &user],
    )
    .expect("stamp invite");
    db.commit();
    Some(user)
}

/// The ledger, newest first: every invite ever minted and what became of it.
pub fn list_invites(db: &Db) -> Vec<InviteRecord> {
    db.query(
        "SELECT i.id, i.note, i.created_at, i.expires_at, i.redeemed_at, i.revoked_at,
                u.id, u.display_name, u.email, u.created_at
           FROM invites i
           LEFT JOIN users u ON u.id = i.user_id
          ORDER BY i.created_at DESC, i.id DESC",
        &[],
    )
    .expect("list_invites")
    .iter()
    .map(|r| InviteRecord {
        id: r.get(0),
        note: r.get(1),
        created_at: r.get(2),
        expires_at: r.get(3),
        redeemed_at: r.get(4),
        revoked_at: r.get(5),
        user: r.get::<_, Option<User>>(6).map(|id| UserRecord {
            id,
            display_name: r.get(7),
            email: r.get(8),
            created_at: r.get(9),
        }),
    })
    .collect()
}

/// Void an unredeemed invite. `false` when there is no such row, or when it
/// has already been taken up — a redeemed invite is history, not access, and
/// the way to shut that door is `revoke_access` on the user it made.
pub fn revoke_invite(db: &Db, id: i64) -> bool {
    db.execute(
        "UPDATE invites SET revoked_at = $2
         WHERE id = $1 AND redeemed_at IS NULL AND revoked_at IS NULL",
        &[&id, &now_seconds()],
    )
    .expect("revoke_invite")
        > 0
}

/// Remove an invite nobody is left of: never opened (voided or expired or
/// merely unwanted), or taken up by a user who has since been removed. The
/// one case refused is a live user behind it — that row is the record of how
/// they got in, and `delete_user` comes first, if at all. `user_id IS NULL`
/// is that whole rule in one predicate, because `ON DELETE SET NULL` is what
/// `user remove` leaves behind.
pub fn delete_invite(db: &Db, id: i64) -> bool {
    db.execute(
        "DELETE FROM invites WHERE id = $1 AND user_id IS NULL",
        &[&id],
    )
    .expect("delete_invite")
        > 0
}

/// The round in flight, as the JSON it was stored as, and the round counter.
pub struct RoundState {
    pub seq: i64,
    pub current: Option<String>,
}

pub fn round_state(db: &Db, user: User) -> RoundState {
    let row = db
        .query_one(
            "SELECT round_seq, current_round FROM users WHERE id = $1",
            &[&user],
        )
        .expect("round_state");
    RoundState {
        seq: row.get(0),
        current: row.get(1),
    }
}

pub fn set_round_state(db: &Db, user: User, seq: i64, current: Option<&str>) {
    db.execute(
        "UPDATE users SET round_seq = $2, current_round = $3 WHERE id = $1",
        &[&user, &seq, &current],
    )
    .expect("set_round_state");
}

pub fn set_current_round(db: &Db, user: User, current: Option<&str>) {
    db.execute(
        "UPDATE users SET current_round = $2 WHERE id = $1",
        &[&user, &current],
    )
    .expect("set_current_round");
}

pub fn set_last_train_at(db: &Db, user: User, at: i64) {
    db.execute(
        "UPDATE users SET last_train_at = $2 WHERE id = $1",
        &[&user, &at],
    )
    .expect("set_last_train_at");
}

/* ----------------------------------------------------------------- stories */

/// The story shape both HN sources normalise into, and `upsert_story` takes.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct Story {
    pub id: i64,
    pub title: String,
    pub url: Option<String>,
    pub domain: Option<String>,
    pub author: Option<String>,
    pub points: i64,
    pub num_comments: i64,
    pub created_at: i64,
    pub day: String,
    pub fetched_at: i64,
}

impl Story {
    /// The ten base columns, in the order `STORY_SELECT` asks for them.
    pub fn from_row(r: &Row) -> Story {
        Story {
            id: r.get(0),
            title: r.get(1),
            url: r.get(2),
            domain: r.get(3),
            author: r.get(4),
            points: r.get(5),
            num_comments: r.get(6),
            created_at: r.get(7),
            day: r.get(8),
            fetched_at: r.get(9),
        }
    }
}

pub const STORY_SELECT: &str =
    "SELECT id, title, url, domain, author, points, num_comments, created_at, day, fetched_at
     FROM stories";

pub fn upsert_story(db: &Db, s: &Story) {
    db.execute(
        "INSERT INTO stories (id, title, url, domain, author, points, num_comments, created_at, day, fetched_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
         ON CONFLICT(id) DO UPDATE SET
           title = excluded.title,
           url = excluded.url,
           domain = excluded.domain,
           points = GREATEST(stories.points, excluded.points),
           num_comments = GREATEST(stories.num_comments, excluded.num_comments),
           fetched_at = excluded.fetched_at",
        &[
            &s.id, &s.title, &s.url, &s.domain, &s.author,
            &s.points, &s.num_comments, &s.created_at, &s.day, &s.fetched_at,
        ],
    )
    .expect("upsert_story");
}

/* ------------------------------------------------------------------- votes */

// A vote is recorded against exactly the submission that was judged. Reposts of
// the same URL are NOT co-signed: the model reads titles, and a twin's title is
// one you never saw. Duplicates are collapsed where they show up instead — the
// training queue (service.rs) offers one card per URL / title.
pub fn record_vote(db: &Db, user: User, story_id: i64, value: i64) {
    record_vote_at(db, user, story_id, value, now_seconds());
}

pub fn record_vote_at(db: &Db, user: User, story_id: i64, value: i64, now: i64) {
    db.execute(
        "INSERT INTO votes (user_id, story_id, value, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT(user_id, story_id) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at",
        &[&user, &story_id, &value, &now, &now],
    )
    .expect("record_vote");
}

// Restoring a vote from an old history: unlike record_vote, the supplied
// timestamp wins on conflict — re-running an import must converge on what the
// export says, not on whenever the first attempt happened to run.
//
// `updated_at` is set to `created_at` too, not to now: a restored vote is the row
// as it was, and nothing has touched it since. Import time is not vote activity,
// and the Votes view reads `updated_at` — stamping it with now made a whole
// restored history read as "voted a minute ago".
pub fn import_vote(db: &Db, user: User, story_id: i64, value: i64, created_at: i64) {
    db.execute(
        "INSERT INTO votes (user_id, story_id, value, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT(user_id, story_id) DO UPDATE SET
           value = excluded.value,
           created_at = excluded.created_at,
           updated_at = excluded.updated_at",
        &[&user, &story_id, &value, &created_at, &created_at],
    )
    .expect("import_vote");
}

pub fn delete_vote(db: &Db, user: User, story_id: i64) {
    db.execute(
        "DELETE FROM votes WHERE user_id = $1 AND story_id = $2",
        &[&user, &story_id],
    )
    .expect("delete_vote");
    // The captured prediction belonged to that vote. Undo means the next
    // judgement gets a fresh one, from whatever the model believes by then.
    db.execute(
        "DELETE FROM vote_predictions WHERE user_id = $1 AND story_id = $2",
        &[&user, &story_id],
    )
    .expect("delete prediction");
}

#[derive(Debug, Clone, Serialize)]
pub struct CapturedPrediction {
    pub score: f64,
    pub confidence: f64,
    #[serde(rename = "modelRev")]
    pub model_rev: i64,
}

/// Freeze what the model currently says about a story, before a vote exists to
/// contaminate it. Returns None when the story has no score yet (nothing
/// honest to claim), which is the normal case before the first model.
pub fn capture_prediction(db: &Db, user: User, story_id: i64) -> Option<CapturedPrediction> {
    let row = db
        .query_opt(
            "SELECT score, confidence, model_rev FROM scores WHERE user_id = $1 AND story_id = $2",
            &[&user, &story_id],
        )
        .expect("capture_prediction read")?;
    let (score, confidence, model_rev): (f64, f64, i64) = (row.get(0), row.get(1), row.get(2));
    db.execute(
        "INSERT INTO vote_predictions (user_id, story_id, score, confidence, model_rev, created_at)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT(user_id, story_id) DO UPDATE SET
           score = excluded.score, confidence = excluded.confidence,
           model_rev = excluded.model_rev, created_at = excluded.created_at",
        &[
            &user,
            &story_id,
            &score,
            &confidence,
            &model_rev,
            &now_seconds(),
        ],
    )
    .expect("capture_prediction write");
    Some(CapturedPrediction {
        score,
        confidence,
        model_rev,
    })
}

/// A labelled story: what the model trains on.
pub struct Labelled {
    pub story: Story,
    pub value: i64,
}

/// Every labelled story (skips excluded) — one user's training set.
///
/// `created_at` is not unique — two votes a second apart in the UI can share a
/// timestamp, and a restored history can carry a whole batch on one — and
/// Postgres promises nothing about ties, so the story id settles them: the
/// training set has to come out in the same order twice for the model to be
/// the deterministic function of the votes it claims to be.
///
/// DESC, which looks arbitrary and is not. It is the order SQLite happened to
/// produce, reverse-scanning `idx_votes_created`, for as long as this ran on
/// SQLite. Example order decides the order features are first seen, and so the
/// whole AdaGrad trajectory: with the other tiebreaker the first retrain after
/// the migration produced a model that scored identically (same features, same
/// cross-validated accuracy to sixteen digits) and weighed everything a little
/// differently. Equally valid, and not what "a retrain reproduces the model"
/// promises. Two votes out of seven hundred were affected; the point is that
/// the number is zero.
pub fn labelled_stories(db: &Db, user: User) -> Vec<Labelled> {
    db.query(
        "SELECT s.id, s.title, s.url, s.domain, s.author, s.points, s.num_comments,
                s.created_at, s.day, s.fetched_at, v.value
         FROM votes v JOIN stories s ON s.id = v.story_id
         WHERE v.user_id = $1 AND v.value != 0
         ORDER BY v.created_at ASC, v.story_id DESC",
        &[&user],
    )
    .expect("labelled_stories")
    .iter()
    .map(|r| Labelled {
        story: Story::from_row(r),
        value: r.get(10),
    })
    .collect()
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct VoteCounts {
    pub up: i64,
    pub down: i64,
    pub skip: i64,
    pub total: i64,
}

pub fn vote_counts(db: &Db, user: User) -> VoteCounts {
    let mut out = VoteCounts {
        up: 0,
        down: 0,
        skip: 0,
        total: 0,
    };
    for r in db
        .query(
            "SELECT value, COUNT(*) AS n FROM votes WHERE user_id = $1 GROUP BY value",
            &[&user],
        )
        .expect("vote_counts")
    {
        let (value, n): (i64, i64) = (r.get(0), r.get(1));
        if value > 0 {
            out.up = n;
        } else if value < 0 {
            out.down = n;
        } else {
            out.skip = n;
        }
    }
    out.total = out.up + out.down + out.skip;
    out
}
